# Generated by Django 4.2.4 on 2023-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='Monthly_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
